name: GitHub Custom Action
run-name: ${{ github.actor }} is testing out Custom GitHub Actions 🚀
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job of custem action
    steps:
      - name: Hello world action step
        id: hello
        uses: decent-infra/shomix-car-action@v1.12
        with:
          spheron-token:  ${{ secrets.SPHERON_TOKEN }}
          cluster-name: "github-action-cluster"
          image-url: "https://hub.docker.com/repository/docker/vocoront/simple-express-server/general"
          image: "vocoront/simple-express-server"
          tag: "v1.0.5"
          health-check-path: "/"
          health-check-port: 3000
          instance-plan-name: "Ventus Nano"
          ports: "8080:80,3000:3000"
          environment-variables: "VAR1=value5,VAR2=value22"
          region: "any"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
