name: GitHub Custom Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job of custem action
    steps:
      - name: Hello world action step
        id: hello
        uses: decent-infra/shomix-car-action@v1.3
        with:
          spheron-token:  ${{ secrets.SPHERON_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
